### ISSUE TITLE
Incorrect timestamp format

### ISSUE THREAD

**Issue by jenseliasson** [eclipse-arrowhead/core-java-spring#264] opened 2020-09-03 06:49 UTC
When I try to register a service using ISO 8601 time format, 
**createdAt":"2020-09-01T20:49:48","updatedAt":"**2020-09-01T20:49:48**"},"serviceUri":"/bordergateway","endOfValidity":"**2020-09-29T21:14:42**","**

I get this error:
{"errorMessage":"End of validity is specified in the wrong format. Please provide UTC time using **yyyy-MM-dd HH:mm:ss** pattern.","errorCode":400,"exceptionType":"BAD_PAYLOAD","origin":"/serviceregistry/register"}

When I remove the 'T' and replace it with a space ' ', it works:
createdAt":"**2020-09-01 20:49:48**","updatedAt":"2020-09-01 20:49:48"},"serviceUri":"/bordergateway","endOfValidity":"2020-09-29 21:14:42","

In the documentation, it says that the timestamp fields must be "ISO 8601 date/time string"
ISO 8601 have the following format (from Wikipedia: "2020-09-03**T**03:35:22+00:00")

In Utilities.java:93
private static final String dateTimePattern = "yyyy-MM-dd HH:mm:ss";

should be
private static final String dateTimePattern = "yyyy-MM-ddTHH:mm:ss";

**Comment by rbocsi** [comment] 2020-09-03 06:57
Duplicate of #193.

**Closed as completed by rbocsi** 2020-09-03 06:57 UTC
Labels: bug, Service Registry
