### ISSUE TITLE
Inconsistent use of endOfValidity

### ISSUE THREAD

**Issue by jenseliasson** [eclipse-arrowhead/core-java-spring#243] opened 2020-07-08 19:53 UTC
The documentation of the tag endOfValidity is confusing. 

One example looks like this:
endOfValidity": "2019-12-05T12:00:00",

This is the ISO format. But in the documentation it often says that endOfValidity is an UTC timestamp. However the type is always string and not a number.

Please clarify.

**Comment by tsvetlin** [comment] 2020-07-09 07:06
Duplicate of #193 
ISO 8601 format will be used in this implementation, it is a string format. You maybe mixing things up with Unix timestamp, which is a number.

**Closed as completed by tsvetlin** 2020-07-09 07:06 UTC
Labels: invalid, documentation

**Comment by jenseliasson** [comment] 2020-07-10 20:46
I am well aware of the difference. But if you Google "UTC timestamp", all hits refer to Unix timestamp. In addition, most programming languages (Python, JavaScript/Node.js, Go, PHP etc), the concept of UTC timestamp is the number of seconds since Jan 1st 1970.

ISO 8601 doesn't even mention "timestamp" if I remember correctly. Normally the terms ,"Date", "Time", "Date and time", and "Datetime" are used when representing the content of ISO 8691 data.

The common use of the term "UTC timestamp" most often means a number. The use of ,"Date", "Time", "Date and time", and "Datetime" most often means a string representation.

Of course there are exceptions, like in SQL and Java. 

Therefore I think it is better to be very clear with names since the term "UTC timestamp" can mean different things for different people. Instead of using the term "UTC timestamp' in the documentation, we could use "Datetime", or "ISO 8601 Datetime" or something similar. Just to avoid confusion.
