### ISSUE TITLE
pull access denied for svetlint/certificateauthority

### ISSUE THREAD

**Issue by pkrasnousov** [eclipse-arrowhead/core-java-spring#305] opened 2021-04-27 09:41 UTC
I am trying to run docker-compose with `core-java-spring/docker/docker-compose.yml` and can not pull `certificateauthority` image. It's missing on `https://hub.docker.com/`  https://hub.docker.com/search?q=svetlint&source=community

**Comment by tsvetlin** [comment] 2021-04-27 09:43
Duplicate of: #271

**Closed as completed by tsvetlin** 2021-04-27 09:43 UTC
