### ISSUE TITLE
Allow certificates  trust chain not finished with arrowhead.eu to be used 

### ISSUE THREAD

**Issue by epmplm** [eclipse-arrowhead/core-java-spring#216] opened 2020-04-30 07:33 UTC
currently the certificates that are used in AHF must contain arrowhead.eu, this can bring up some issues when the framework is used in big organisations.  For example I should be allowed use the company that I work at url in the trust chain.

**Comment by tsvetlin** [comment] 2020-04-30 07:50
Duplicate of #198 
See: https://github.com/arrowhead-f/core-java-spring/issues/198#issuecomment-616377676

Could you please explain in detail?

**Comment by epmplm** [comment] 2020-04-30 08:02
This is from the certificate paragraph
Arrowhead Framework's security is relying on SSL Certificate Trust Chains. The Arrowhead trust chain consists of three level:

Master certificate: arrowhead.eu
Cloud certificate: my_cloud.my_company.arrowhead.eu
Client certificate: my_client.my_cloud.my_company.arrowhead.eu The certificate naming convention have strict rules:

In our project we created a master certificated as jotne.com which cause the system to not recognise the certificate. We made a new one as arrowhead.eu and everything started to work correctly

**Comment by tsvetlin** [comment] 2020-04-30 08:08
This is the expected behaviour. Documentation is crystal clear about it.

**Closed as completed** 2020-04-30 08:22 UTC
